USE rpm_database;
-- PATIENTS
CREATE TABLE patients (
    Id CHAR(36) PRIMARY KEY,
    FIRST VARCHAR(50),
    MIDDLE VARCHAR(50),
    LAST VARCHAR(50),
    BIRTHDATE DATE,
    DEATHDATE DATE,
    GENDER VARCHAR(50),
    RACE VARCHAR(255),
    ETHNICITY VARCHAR(255),
    ADDRESS TEXT,
    CITY VARCHAR(255),
    STATE VARCHAR(2),
    ZIP VARCHAR(10),
    MARITAL VARCHAR(50)
) ENGINE=InnoDB;

-- ORGANIZATIONS
CREATE TABLE organizations (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS TEXT,
    CITY VARCHAR(255),
    STATE VARCHAR(2),
    ZIP VARCHAR(10),
    PHONE VARCHAR(20)
) ENGINE=InnoDB;

-- PROVIDERS
CREATE TABLE providers (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    GENDER VARCHAR(10),
    SPECIALTY VARCHAR(255),
    ADDRESS TEXT,
    CITY VARCHAR(255),
    STATE VARCHAR(2),
    ZIP VARCHAR(10)
) ENGINE=InnoDB;

-- ENCOUNTERS
CREATE TABLE encounters (
    Id CHAR(36) PRIMARY KEY,
    START TIMESTAMP,
    STOP TIMESTAMP,
    PATIENT CHAR(36),
    ORGANIZATION CHAR(36),
    PROVIDER CHAR(36),
    ENCOUNTERCLASS VARCHAR(50),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ORGANIZATION) REFERENCES organizations(Id),
    FOREIGN KEY (PROVIDER) REFERENCES providers(Id)
) ENGINE=InnoDB;

-- CONDITIONS
CREATE TABLE conditions (
    START DATE,
    STOP DATE,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;

-- MEDICATIONS
CREATE TABLE medications (
    START TIMESTAMP,
    STOP TIMESTAMP,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;

-- OBSERVATIONS
CREATE TABLE observations (
    DATE TIMESTAMP,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    VALUE VARCHAR(255),
    UNITS VARCHAR(50),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;

# -- CLINICAL_NOTES (Key for LLM)
CREATE TABLE IF NOT EXISTS clinical_notes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id CHAR(36),
    date DATETIME,
    chief_complaint TEXT,
    history_of_illness TEXT,
    social_history TEXT,
    allergies TEXT,
    medications TEXT,
    assessment TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(Id)
) ENGINE=InnoDB;

-- PROCEDURES
CREATE TABLE procedures (
    DATE TIMESTAMP,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;

-- IMMUNIZATIONS
CREATE TABLE immunizations (
    DATE TIMESTAMP,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;

-- ALLERGIES
CREATE TABLE allergies (
    START DATE,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
) ENGINE=InnoDB;


-- INDEXES (Optimized for MySQL)
CREATE INDEX idx_encounters_patient ON encounters(PATIENT);
CREATE INDEX idx_encounters_org ON encounters(ORGANIZATION);
CREATE INDEX idx_encounters_provider ON encounters(PROVIDER);
CREATE INDEX idx_conditions_patient ON conditions(PATIENT);
CREATE INDEX idx_medications_patient ON medications(PATIENT);
CREATE INDEX idx_observations_patient ON observations(PATIENT);
CREATE INDEX idx_notes_patient ON clinical_notes(patient_id);